### ISSUE TITLE
0.6.14 - can't get a generated file from the tasks

### ISSUE THREAD

**Issue by clearsitedesigns** [filamentgroup/grunticon#100]
This is my first foray into grunticon so I could be doing something wrong.

I was trying to get grunticon working with a project and believe I have my coffee script task setup correct. I run the task "makeicons" I get a fatal error. Even verbose tells me that "provide grunticon configuration for src and dest in your grunt.js" - which as you can see below that is configured and both src and dest dirs exist.

```
  grunticon:
    icons:
      files:
        src: "resources/custom/icons"
        dest: "assets/img/icons"
        options:
          pngfolder:"/assets/img/png/"
```
