### ISSUE TITLE
Option to have css classes contain svg height and width

### ISSUE THREAD

**Issue by tracycummins** [filamentgroup/grunticon#133]
Hello,

Is it possible that grunticon have an option to have the svg's height and width set in the svg.css result?  For example:

.icon-my-image {
    background-image: url('data:image/svg+xml;charset=US-ASCII,...');
    background-repeat: no-repeat;
        height: 40px;
        width: 40px;
}

I would need this so that I don't have to set the height and width of the div as the svg icon already designed with a size in mind.

Thanks a lot.

**Comment by nicholasbg** [comment]
I'm having trouble getting the width and height to show in the css file. This is the straight copy-paste of the options I'm using:
```
{{#each customselectors}}{{this}},{{/each}}
{{prefix}}{{name}} {
	background-image: url('{{datauri}}');
	background-repeat: no-repeat;
	width: {{width}}px;
	height: {{height}}px;
}
```
and this is the output for each of my css classes:

```
.icon-thing {
	background-image: url('data:image/svg+xml; ... ');
	background-repeat: no-repeat;
	width: px;
	height: px;
}

```
As you can see, width and height are missing... It might be worth noting that the width and height do show up properly in the preview.html.

Any suggestions?

**Comment by jefflembeck** [comment]
Bizarre. I just tried with:

```css
{{#each customselectors}}{{this}},{{/each}}
{{prefix}}{{name}} {
	background-image: url('{{datauri}}');
	background-repeat: no-repeat;
	width: {{width}};
	height: {{height}};
}
```
Can you upload one of your SVGs? @nicholasbg
