### ISSUE TITLE
SVG Sprites

### ISSUE THREAD

**Issue by grayghostvisuals** [filamentgroup/grunticon#140]
Produce true SVG sprites where the cartesian coordinates and size are given to an author in CSS, Sass or LESS output? Basically exactly like Compass does currently with .png. Let me know if I'm talking crazy town here or not. :v: 

**example**
```css
.icons-sprite, .icons-building, .icons-camera {
  background-image: url(computer barf goes here);
  background-repeat: no-repeat;
}

.icons-building {
  background-position: 0 0;
  height: 156px;
  width: 156px;
}

.icons-camera {
  background-position: 0 -156px;
  height: 156px;
  width: 156px;
}
```
