### ISSUE TITLE
new colors management and css pseudoclasses

### ISSUE THREAD

**Issue by GianlucaGuarini** [filamentgroup/grunticon#144]
https://github.com/filamentgroup/directory-colorfy/pull/3#issuecomment-38016249

I am working on 3 new grunticon features:

###### Input:
-- close.svg
-- arrow-down.svg
-- arrow-up.svg
######  grunticon configuration:
```javascript
grunticon {
   options: {
        colorsInFileName:false,
        colors: {
            'primary': 'green',
            ':hover': 'red'
        }   
    }
}
```
###### output:
```css
.close {
    background: close icon color;
}
.close:hover {
    background: close-hover color;
}
.close.primary {
   background: close-primary color;
}
.arrow {
    background: arrow icon color;
}
.arrow:hover {
    background: arrow-hover color;
}
.arrow.primary {
   background: arrow-primary color;
}
..and so on..
```

###### Input:
-- close.svg
-- arrow-down.svg
-- arrow-up.svg

######  grunticon configuration:
```javascript
grunticon {
   options: {
        colorsInFileName:false,
        colors: {
            ':focus': 'green',
            ':hover': 'red'
        }   
    }
}
```
###### output:
```css
.close {
    background: close icon color;
}
.close:hover {
    background: close-hover color;
}
.close:focus {
   background: close-focus color;
}
.arrow {
    background: arrow icon color;
}
.arrow:hover {
    background: arrow-hover color;
}
.arrow:focus {
   background: arrow-focus color;
}
..and so on..
```

###### Input:
-- close.svg
-- arrow-down.svg
-- arrow-up.svg

######  grunticon configuration:
```javascript
grunticon {
   options: {
        colorsInFileName:false,
        colors: {
            'primary': 'green'
        }   
    }
}
```
###### output:
```css
.close {
    background: close icon color;
}
.close.primary {
    background: close-primary color;
}

.arrow {
    background: arrow icon color;
}
.arrow.primary {
    background: arrow-primary color;
}

..and so on..
```
