### ISSUE TITLE
how to set width of svg using grunticon 

### ISSUE THREAD

**Issue by vitaly87** [filamentgroup/grunticon#313]
Hi all!
I am using svg via grunticon, and I want to set the hight and width to 100% from svg tag,
can it be done by configuration or any other fast way? 
I am using grunticon.loader.js.

**Comment by dominikwilkowski** [comment]
Hey @vitaly87 

I would ask on [StackOverflow](http://stackoverflow.com/) as issues in GitHub are more for bug tracking.

To your question: I would embed the svg and then add height and width to the svg via CSS.

**Comment by vitaly87** [comment]
I asked but still didnt get any reply

**Comment by jefflembeck** [comment]
There is no direct way via grunticon to do this, but like @dominikwilkowski mentioned, you can use CSS if the svg is embedded.

**Comment by vitaly87** [comment]
can you show an example how to use it via css?

**Comment by dominikwilkowski** [comment]
@vitaly87 without having code infront of me to test I would do something like that:

In your HTML:
```HTML
<span class="icon icon-size-full icon-face-happy" data-grunticon-embed></span>
```

In your CSS:
```Less
.icon {
	display: inline-block;
	width: 32px;
	height: 32px;

	&.icon-size-full {
		background-size: 100% auto;
		width: 100%;
		height: auto;

		svg {
			width: 100%;
			height: auto;
		}
	}
}
```

Hope it helps
