### ISSUE TITLE
Multiple class names support?

### ISSUE THREAD

**Issue by gillesdemey** [filamentgroup/grunticon#45]
Would it be possible to support multiple class names for SVG icons that look the same but are named differently?

ie. the same SVG icon with different file names will become something like:

``` css
.ico_lightbulb.off, .ico_lightbulb.disabled {
 background-image: url(...);
}
```
